wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.17.7
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724778019
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      3:
      - 23
      4: 3.12.0
      5: 0.17.7
      6: 4.44.2
      8:
      - 3
      - 5
      13: windows-amd64
